routes.py
import json
from os import scandir
from os.path import basename
from random import choice

from flask_login import current_user, login_required, login_user, logout_user
from app import db, redis, flagsmith
import models
from forms import *
import helper
from flask import (
    request,
    send_from_directory,
    render_template,
    redirect,
    url_for,
    Response,
    Blueprint,
)

from wtforms import ValidationError
#from dls1_client import Client
from base64 import b64encode, b64decode

from pickle import dumps
from gsid import gsid_dec, gsid_enc
from os.path import exists
from werkzeug.security import generate_password_hash, check_password_hash

# import redis
from constants import *
from flask_babel import _
from requests import post

from uuid import uuid1

from json import load

from random import randint, choice

from operator import itemgetter

main_routes = Blueprint("main_routes", __name__)

pkmn_pool = load(open("pkm_pool.json"))

def get_flags():
    traits={"playtime": 0, "logged_in": 1}
    if current_user.is_anonymous:
        identity = f"anon_user_{str(uuid1())}"
        traits["logged_in"] = 0
        
    else:
        identity = str(current_user.id)
    return flagsmith.get_identity_flags(identifier=identity, traits=traits)

@main_routes.route("/")
def home():
    userflags = get_flags()
    # return 'Hello there! This page is under construction! Why not check out <a href="https://web.archive.org/web/20110715101524id_/http://www.pokemon-gl.com/languages/">what remains of PGL</a> while you wait?'
    return render_template("home.html.jinja2", title=_("Home"), userflags=userflags)


@main_routes.route("/savedata", methods=["GET", "POST"])
def savedata():
    userflags = get_flags()
    form = LinkForm()
    if form.validate_on_submit():
        return redirect(
            url_for("main_routes.get_savedata", trainerid=gsid_dec(form.gsid.data))
        )
    return render_template(
        "savedata.html.jinja2", form=form, title=_("Manage Save Data"),
        userflags=userflags
    )


@main_routes.route("/savedata/<trainerid>")
def get_savedata(trainerid):
    u = models.GSUser.query.filter_by(id=trainerid).first()
    if u == None:
        if exists(f"saves/savdata-{trainerid}.sav"):
            return send_from_directory("saves", f"savdata-{trainerid}.sav")
    return send_from_directory("saves", f"savdata-{u.id}.sav")


@main_routes.route("/radar")
@login_required
def use_radar():
    # Basic functionality for catching Pokemon
    rows = []
    for row in range(5):
        row_list = []
        for column in range(5):
            mode = randint(0, 4)
            if 0 <= mode <= 2:
                row_list.append("standard" + str(randint(0, len(pkmn_pool["standard"]) - 1)))
            if mode == 3:
                row_list.append("sparkle" + str(randint(0, len(pkmn_pool["sparkle"]) - 1)))
            if mode == 4:
                row_list.append("no")
        rows.append(row_list)
    userflags = get_flags()
    if bool(int(userflags.get_feature_value("enable_poke_radar"))):
        return render_template(
            "radar.html.jinja2",
            rows=rows,
            userflags=userflags
        )
    else:
        return "Your account does not have this feature enabled."


@main_routes.route("/patch/<patch>")
@login_required
def catch_from_patchno(patch):
    userflags = get_flags()
    if bool(int(userflags.get_feature_value("enable_poke_radar"))):
        if not patch == "no":
            index = int(patch[-1])
            pokemon = pkmn_pool[patch[:-1]][index]
            pokename, pokeid, form, gender, animation = itemgetter("name", "species", "form", "gender", "animation")(pokemon)
            gu = models.GSUser.query.filter_by(uid=current_user.id).first()
            gu.pokemon0 = helper.Pokemon(1, pokeid, b"\x00", b"\x02", 1, b"\x00").to_b64()
            # hope this works

            db.session.add(gu)
            db.session.commit()
            return f"You got a {pokename}!"
        else:
            return "There was no Pokemon in that patch :("
    else:
        return "Your account does not have this feature enabled."


# @app.route("/users")
# def users():
#    return f"Hello! To view user information, go to {url_for('users')}/<your GSID>. For instance, if your GSID is AAAAAAA2EE, go to {url_for('users')}/AAAAAAA2EE. Note: this will have a better look soon!"


@main_routes.route("/users/<gsid>")
def user_gsid(gsid):
    userflags = get_flags()
    gu = models.GSUser.query.filter_by(id=gsid).first()
    u = models.User.query.filter_by(id=gu.uid).first()
    return render_template(
        "user.html.jinja2", title=_("User ") + u.username, user=u, gsuser=gu,
        userflags=userflags
    )


@main_routes.route("/users/me")
def user_me():
    userflags = get_flags()
    u = models.User.query.filter_by(id=current_user.id).first()
    gu = models.GSUser.query.filter_by(uid=current_user.id).first()  #
    return render_template(
        "user.html.jinja2", title=_("User ") + u.username, user=u, gsuser=gu,
        userflags=userflags
    )


@main_routes.route("/link", methods=["GET", "POST"])
def link_gsid():
    userflags = get_flags()
    form = LinkPwForm()
    if form.validate_on_submit():
        gu = models.GSUser.query.filter_by(id=gsid_dec(form.gsid.data)).first()
        u = models.User(
            username=form.username.data,
            password_hash=generate_password_hash(form.password.data),
        )
        gu.user = u
        db.session.add(u)
        db.session.commit()
        return redirect(url_for("main_routes.home"))
    return render_template("link.html.jinja2", title=_("Link GSID"), form=form, userflags=userflags)


@main_routes.route("/login", methods=["GET", "POST"])
def login():
    userflags = get_flags()
    form = LoginForm()
    if form.validate_on_submit():
        u = models.User.query.filter_by(username=form.username.data).first()
        if u == None:
            raise ValidationError(
                "Invalid username! Your trainer name is the one you used during account link."
            )
        if not check_password_hash(u.password_hash, form.password.data):
            raise ValidationError("Invalid password!")
        login_user(u)
        return redirect(url_for("main_routes.home"))
    return render_template("login.html.jinja2", title=_("Login"), form=form, userflags=userflags)


@main_routes.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main_routes.home"))


@main_routes.route("/pokemon/validate", methods=["GET", "POST"])
def validate_pokemon():
    return "\x00"

templates/404.html.jinja2
{% extends "base.html.jinja2" %}
{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{{ url_for('main_routes.home') }}">{{ _('Home') }}</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbGsDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Game Sync') }}</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            <a class="dropdown-item disabled" href="#">{{ _('Dream Land') }}</a>
            <a class="dropdown-item disabled" href="#">{{ _('Global Battle Union') }}</a>
        </ul>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbLoginDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Account') }}</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            {% if current_user.is_anonymous %}
            <a class="dropdown-item" href="{{ url_for('main_routes.login') }}">{{ _("Sign In") }}</a>
            <a class="dropdown-item" href="{{ url_for('main_routes.link_gsid') }}">{{ _("Link Save Data") }}</a>
            {% else %}
            <a class="dropdown-item" href="{{ url_for('main_routes.logout') }}">{{ _("Sign Out") }}</a>
            {% endif %}
            {% if not current_user.is_anonymous %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('main_routes.user_me') }}">{{ _("Trainer Info") }}</a>
            {% endif %}
        </ul>
    </li>
{% endblock %}
{% block content %}
    <h1>{{ _("404: Dubious Disc Not Found") }}</h1>
    <p>{{ _("You seem to have forgotten to get the Old Sea Map! Maybe try heading back home?") }}</p>
    <p>{{ _("The page you were looking for was not found.") }}</p>
{% endblock %}

templates/base.html.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block metas %}{% endblock %}
    <title>{{ title }} | DSLink</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}">

    {% block styles %}{% endblock %}
    {% block scripts %}{% endblock %}
    {% block head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main_routes.home') }}">DSLink</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% block navbar %}{% endblock navbar %}
                </ul>
            </div>
        </div>
    </nav>
    {% block precontainer %}{% endblock %}
    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>
</body>

templates/home.html.jinja2
{% extends "base.html.jinja2" %}
{% block navbar %}
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">{{ _('Home') }}</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbGsDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Game Sync') }}</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            <a class="dropdown-item disabled" href="#">{{ _('Dream Land') }}</a>
            <a class="dropdown-item disabled" href="#">{{ _('Global Battle Union') }}</a>
            {% if userflags.get_feature_value("enable_poke_radar") == 1 and not current_user.is_anonymous %}
            <a class="dropdown-item" href="{{ url_for('main_routes.use_radar') }}">{{ _('Poke Radar') }}</a>
            {% endif %}
        </ul>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbLoginDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Account') }}</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            {% if current_user.is_anonymous %}
            <a class="dropdown-item" href="{{ url_for('main_routes.login') }}">{{ _("Sign In") }}</a>
            <a class="dropdown-item" href="{{ url_for('main_routes.link_gsid') }}">{{ _("Link Save Data") }}</a>
            {% else %}
            <a class="dropdown-item" href="{{ url_for('main_routes.logout') }}">{{ _("Sign Out") }}</a>
            {% endif %}
            {% if not current_user.is_anonymous %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('main_routes.user_me') }}">{{ _("Trainer Info") }}</a>
            {% endif %}
        </ul>
    </li>
{% endblock %}
{% block content %}
    <h1>{{ _("Hello!") }}</h1>
    <p>{{ _("Welcome to DSLink's Game Sync main page!") }}</p>
{% endblock %}

templates/link.html.jinja2
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html.jinja2" %}
{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{{ url_for('main_routes.home') }}">{{ _('Home') }}</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbGsDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Game Sync') }}</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            <a class="dropdown-item disabled" href="#">{{ _('Dream Land') }}</a>
            <a class="dropdown-item disabled" href="#">{{ _('Global Battle Union') }}</a>
            {% if userflags.get_feature_value("enable_poke_radar") == 1 and not current_user.is_anonymous %}
            <a class="dropdown-item" href="{{ url_for('main_routes.use_radar') }}">{{ _('Poke Radar') }}</a>
            {% endif %}
        </ul>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbLoginDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Account</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            {% if current_user.is_anonymous %}
            <a class="dropdown-item" href="{{ url_for('main_routes.login') }}">{{ _("Sign In") }}</a>
            <a class="dropdown-item active" href="#">{{ _("Link Save Data") }}</a>
            {% else %}
            <a class="dropdown-item" href="{{ url_for('main_routes.logout') }}">{{ _("Sign Out") }}</a>
            {% endif %}
            {% if not current_user.is_anonymous %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('main_routes.user_me') }}">{{ _("Trainer Info") }}</a>
            {% endif %}
        </ul>
    </li>
{% endblock %}
{% block content %}
    {{ wtf.quick_form(form) }}
{% endblock %}

templates/login.html.jinja2
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html.jinja2" %}
{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{{ url_for('main_routes.home') }}">{{ _('Home') }}</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbGsDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Game Sync') }}</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            <a class="dropdown-item disabled" href="#">{{ _('Dream Land') }}</a>
            <a class="dropdown-item disabled" href="#">{{ _('Global Battle Union') }}</a>
            {% if userflags.get_feature_value("enable_poke_radar") == 1 and not current_user.is_anonymous %}
            <a class="dropdown-item" href="{{ url_for('main_routes.use_radar') }}">{{ _('Poke Radar') }}</a>
            {% endif %}
        </ul>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbLoginDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Account</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            {% if current_user.is_anonymous %}
            <a class="dropdown-item active" href="#">{{ _("Sign In") }}</a>
            <a class="dropdown-item" href="{{ url_for('main_routes.link_gsid') }}">{{ _("Link Save Data") }}</a>
            {% else %}
            <a class="dropdown-item" href="{{ url_for('main_routes.logout') }}">{{ _("Sign Out") }}</a>
            {% endif %}
            {% if not current_user.is_anonymous %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('main_routes.user_me') }}">{{ _("Trainer Info") }}</a>
            {% endif %}
        </ul>
    </li>
{% endblock %}
{% block content %}
    {{ wtf.quick_form(form) }}
{% endblock %}

templates/maintance.html.jinja2
{% extends "base.html.jinja2" %}
{% block content %}
    <h1>{{ _("Pardon our Porygon!") }}</h1>
    <p>{{ _("We're sorry, but we are undergoing maintaince right now!") }}</p>
{% endblock %}

templates/radar.html.jinja2
<!-- PokeRadar functionality -->

{% extends "base.html.jinja2" %}
{% block navbar %}
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">{{ _('Home') }}</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbGsDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Game Sync') }}</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            <a class="dropdown-item disabled" href="#">{{ _('Dream Land') }}</a>
            <a class="dropdown-item disabled" href="#">{{ _('Global Battle Union') }}</a>
            {% if userflags.get_feature_value("enable_poke_radar") == 1 and not current_user.is_anonymous %}
            <a class="dropdown-item" href="#">{{ _('Poke Radar') }}</a>
            {% endif %}
        </ul>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbLoginDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Account') }}</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            {% if current_user.is_anonymous %}
            <a class="dropdown-item" href="{{ url_for('main_routes.login') }}">{{ _("Sign In") }}</a>
            <a class="dropdown-item" href="{{ url_for('main_routes.link_gsid') }}">{{ _("Link Save Data") }}</a>
            {% else %}
            <a class="dropdown-item" href="{{ url_for('main_routes.logout') }}">{{ _("Sign Out") }}</a>
            {% endif %}
            {% if not current_user.is_anonymous %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('main_routes.user_me') }}">{{ _("Trainer Info") }}</a>
            {% endif %}
        </ul>
    </li>
{% endblock %}
{% block content %}
    <h1>{{ _("Pick a patch") }}</h1>
    {% for row in rows %}
        {% for patch in row %}
            <a href="/patch/{{ patch }}">
            {% if "sparkle" in patch %}
                <img src="{{ url_for('static', filename='img/radar_grass_rarepkmn.png') }}">
            {% elif "no" in patch %}
                <img src="{{ url_for('static', filename='img/radar_grass_nopkmn.png') }}">
            {% elif "standard" in patch %}
                <img src="{{ url_for('static', filename='img/radar_grass_pkmn.png') }}">
            {% endif %}
            </a>
        {% endfor %}
        <br>
    {% endfor %}
{% endblock %}

templates/savedata.html.jinja2
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html.jinja2" %}
{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{{ url_for('main_routes.home') }}">{{ _('Home') }}</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbGsDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Game Sync') }}</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            <a class="dropdown-item disabled" href="#">{{ _('Dream Land') }}</a>
            <a class="dropdown-item disabled" href="#">{{ _('Global Battle Union') }}</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item active" href="#">{{ _("Download Save Data") }}</a> <!-- gs_savdownload is completely different from savedata.download. Be careful! -->
            {% if userflags.get_feature_value("enable_poke_radar") == 1 and not current_user.is_anonymous %}
            <a class="dropdown-item" href="{{ url_for('main_routes.use_radar') }}">{{ _('Poke Radar') }}</a>
            {% endif %}
        </ul>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbLoginDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Account') }}</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            <a class="dropdown-item" href="{{ url_for('main_routes.login') }}">{{ _("Sign In") }}</a>
            <a class="dropdown-item" href="{{ url_for('main_routes.link_gsid') }}">{{ _("Link Save Data") }}</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item disabled" href="#">{{ _("Trainer Info") }}</a>
        </ul>
    </li>
{% endblock %}
{% block content %}
    {{ wtf.quick_form(form) }}
{% endblock %}

templates/select_gearskin2.html.jinja2
{% extends "base.html.jinja2" %}
{% block navbar %}
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">{{ _('Home') }}</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbGsDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Game Sync') }}</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            <a class="dropdown-item disabled" href="#">{{ _('Dream Land') }}</a>
            <a class="dropdown-item disabled" href="#">{{ _('Global Battle Union') }}</a>
            {% if userflags.get_feature_value("enable_poke_radar") == 1 and not current_user.is_anonymous %}
            <a class="dropdown-item" href="{{ url_for('main_routes.use_radar') }}">{{ _('Poke Radar') }}</a>
            {% endif %}
        </ul>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbLoginDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Account') }}</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            {% if current_user.is_anonymous %}
            <a class="dropdown-item" href="{{ url_for('main_routes.login') }}">{{ _("Sign In") }}</a>
            <a class="dropdown-item" href="{{ url_for('main_routes.link_gsid') }}">{{ _("Link Save Data") }}</a>
            {% else %}
            <a class="dropdown-item" href="{{ url_for('main_routes.logout') }}">{{ _("Sign Out") }}</a>
            {% endif %}
            {% if not current_user.is_anonymous %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('main_routes.user_me') }}">{{ _("Trainer Info") }}</a>
            {% endif %}
        </ul>
    </li>
{% endblock %}
{% block content %}
    <h1>{{ _("C-GEAR Skin") }}</h1>
    <p>{{ _("Please select a skin to download.") }}</p>
    {% for skin in skins %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title" style="color: var(--bs-dark);">{{ skin.name }}</h5>
                <a href="#"><img src="{{ skin.image_url }}" alt="{{ skin.name }}" class=""/></a>
            </div>
        </div>
    {% endfor %}     
{% endblock %}

templates/user.html.jinja2
{% extends "base.html.jinja2" %}
{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{{ url_for('main_routes.home') }}">{{ _('Home') }}</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbGsDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Game Sync') }}</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            <a class="dropdown-item disabled" href="#">{{ _('Dream Land') }}</a>
            <a class="dropdown-item disabled" href="#">{{ _('Global Battle Union') }}</a>
            {% if userflags.get_feature_value("enable_poke_radar") == 1 and not current_user.is_anonymous %}
            <a class="dropdown-item" href="{{ url_for('main_routes.use_radar') }}">{{ _('Poke Radar') }}</a>
            {% endif %}
        </ul>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="nbLoginDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Account') }}</a>
        <ul class="dropdown-menu" aria-labelledby="nbGsDropdown">
            {% if current_user.is_anonymous %}
            <a class="dropdown-item" href="{{ url_for('main_routes.login') }}">{{ _("Sign In") }}</a>
            <a class="dropdown-item" href="{{ url_for('main_routes.link_gsid') }}">{{ _("Link Save Data") }}</a>
            {% else %}
            <a class="dropdown-item" href="{{ url_for('main_routes.logout') }}">{{ _("Sign Out") }}</a>
            {% endif %}
            {% if not current_user.is_anonymous %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item active" href="#">{{ _("Trainer Info") }}</a>
            {% endif %}
        </ul>
    </li>
{% endblock %}
{% block content %}
    <h1>P<sub>K</sub>M<sub>N</sub> {{ _("Trainer") }} {{ user.username }}</h1>
    {% if gsuser.gamever == 20 %}
        <img src="{{ url_for('static', filename='img/bw_zekrom.png') }}" alt="Zekrom" class="img-fluid"/>
    {% elif gsuser.gamever == 21 %}
        <img src="{{ url_for('static', filename='img/bw_reshiram.png') }}" alt="Reshiram" class="img-fluid"/>
    {% elif gsuser.gamever == 22 %}
        <img src="{{ url_for('static', filename='img/b2w2_wk.png') }}" alt="White Kyurem" class="img-fluid"/>
    {% elif gsuser.gamever == 23 %}
        <img src="{{ url_for('static', filename='img/b2w2_bk.png') }}" alt="Black Kyurem" class="img-fluid"/>
    {% else %}
        <p>Legacy Account</p>
    {% endif %}
{% endblock %}